export const GET_EXPERIENCE_DATA = 'GET_EXPERIENCE_DATA';
export const GET_EXPERIENCE_DATA_SUCCESS = 'GET_EXPERIENCE_DATA_SUCCESS';
export const GET_EXPERIENCE_DATA_FAILURE = 'GET_EXPERIENCE_DATA_FAILURE';

export const GET_EXPERIENCE_BY_ID = 'GET_EXPERIENCE_BY_ID';
export const GET_EXPERIENCE_BY_ID_SUCCESS = 'GET_EXPERIENCE_BY_ID_SUCCESS';
export const GET_EXPERIENCE_BY_ID_FAILURE = 'GET_EXPERIENCE_BY_ID_FAILURE';

export const CREATE_EXPERIENCE = 'CREATE_EXPERIENCE';
export const CREATE_EXPERIENCE_SUCCESS = 'CREATE_EXPERIENCE_SUCCESS';
export const CREATE_EXPERIENCE_FAILURE = 'CREATE_EXPERIENCE_FAILURE';

export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
export const DELETE_EXPERIENCE_FAILURE = 'DELETE_EXPERIENCE_FAILURE';

export const UPDATE_EXPERIENCE = 'UPDATE_EXPERIENCE';
export const UPDATE_EXPERIENCE_SUCCESS = 'UPDATE_EXPERIENCE_SUCCESS';
export const UPDATE_EXPERIENCE_FAILURE = 'UPDATE_EXPERIENCE_FAILURE';

export const REORDER_EXPERIENCE = 'REORDER_EXPERIENCE';
export const REORDER_EXPERIENCE_SUCCESS = 'REORDER_EXPERIENCE_SUCCESS';
export const REORDER_EXPERIENCE_FAILURE = 'REORDER_EXPERIENCE_FAILURE';

export const TOGGLE_CANCELLATION_POLICY = 'TOGGLE_CANCELLATION_POLICY';
export const TOGGLE_CANCELLATION_POLICY_SUCCESS = 'TOGGLE_CANCELLATION_POLICY_SUCCESS';
export const TOGGLE_CANCELLATION_POLICY_FAILURE = 'TOGGLE_CANCELLATION_POLICY_FAILURE';

export const TOGGLE_INCLUSION = 'TOGGLE_INCLUSION';
export const TOGGLE_INCLUSION_SUCCESS = 'TOGGLE_INCLUSION_SUCCESS';
export const TOGGLE_INCLUSION_FAILURE = 'TOGGLE_INCLUSION_FAILURE';

export const ASSOCIATE_LOCATION = 'ASSOCIATE_LOCATION';
export const ASSOCIATE_LOCATION_SUCCESS = 'ASSOCIATE_LOCATION_SUCCESS';
export const ASSOCIATE_LOCATION_FAILURE = 'ASSOCIATE_LOCATION_FAILURE';

export const UPDATE_EXPERIENCE_LOCATION = 'UPDATE_EXPERIENCE_LOCATION';
export const UPDATE_EXPERIENCE_LOCATION_SUCCESS = 'UPDATE_EXPERIENCE_LOCATION_SUCCESS';
export const UPDATE_EXPERIENCE_LOCATION_FAILURE = 'UPDATE_EXPERIENCE_LOCATION_FAILURE';

export const DISASSOCIATE_LOCATION = 'DISASSOCIATE_LOCATION';
export const DISASSOCIATE_LOCATION_SUCCESS = 'DISASSOCIATE_LOCATION_SUCCESS';
export const DISASSOCIATE_LOCATION_FAILURE = 'DISASSOCIATE_LOCATION_FAILURE';

export const TOGGLE_ADDON = 'TOGGLE_ADDON';
export const TOGGLE_ADDON_SUCCESS = 'TOGGLE_ADDON_SUCCESS';
export const TOGGLE_ADDON_FAILURE = 'TOGGLE_ADDON_FAILURE';

export const GET_EXPERIENCE_ADDONS = 'GET_EXPERIENCE_ADDONS';
export const GET_EXPERIENCE_ADDONS_SUCCESS = 'GET_EXPERIENCE_ADDONS_SUCCESS';
export const GET_EXPERIENCE_ADDONS_FAILURE = 'GET_EXPERIENCE_ADDONS_FAILURE';

export const TOGGLE_EXPERIENCE_ACTIVE = 'TOGGLE_EXPERIENCE_ACTIVE';
export const TOGGLE_EXPERIENCE_ACTIVE_SUCCESS = 'TOGGLE_EXPERIENCE_ACTIVE_SUCCESS';
export const TOGGLE_EXPERIENCE_ACTIVE_FAILURE = 'TOGGLE_EXPERIENCE_ACTIVE_FAILURE';

export const TOGGLE_EXPERIENCE_FEATURED = 'TOGGLE_EXPERIENCE_FEATURED';
export const TOGGLE_EXPERIENCE_FEATURED_SUCCESS = 'TOGGLE_EXPERIENCE_FEATURED_SUCCESS';
export const TOGGLE_EXPERIENCE_FEATURED_FAILURE = 'TOGGLE_EXPERIENCE_FEATURED_FAILURE';

export const BULK_ATTACH_MEDIA = 'BULK_ATTACH_MEDIA';
export const BULK_ATTACH_MEDIA_SUCCESS = 'BULK_ATTACH_MEDIA_SUCCESS';
export const BULK_ATTACH_MEDIA_FAILURE = 'BULK_ATTACH_MEDIA_FAILURE';

export const DISASSOCIATE_MEDIA = 'DISASSOCIATE_MEDIA';
export const DISASSOCIATE_MEDIA_SUCCESS = 'DISASSOCIATE_MEDIA_SUCCESS';
export const DISASSOCIATE_MEDIA_FAILURE = 'DISASSOCIATE_MEDIA_FAILURE';

export const GET_EXPERIENCE_MEDIA = 'GET_EXPERIENCE_MEDIA';
export const GET_EXPERIENCE_MEDIA_SUCCESS = 'GET_EXPERIENCE_MEDIA_SUCCESS';
export const GET_EXPERIENCE_MEDIA_FAILURE = 'GET_EXPERIENCE_MEDIA_FAILURE';

export const ATTACH_MEDIA = 'ATTACH_MEDIA';
export const ATTACH_MEDIA_SUCCESS = 'ATTACH_MEDIA_SUCCESS';
export const ATTACH_MEDIA_FAILURE = 'ATTACH_MEDIA_FAILURE';

export const UPDATE_MEDIA_ATTACHMENT = 'UPDATE_MEDIA_ATTACHMENT';
export const UPDATE_MEDIA_ATTACHMENT_SUCCESS = 'UPDATE_MEDIA_ATTACHMENT_SUCCESS';
export const UPDATE_MEDIA_ATTACHMENT_FAILURE = 'UPDATE_MEDIA_ATTACHMENT_FAILURE';

export const TOGGLE_MEDIA_ACTIVE = 'TOGGLE_MEDIA_ACTIVE';
export const TOGGLE_MEDIA_ACTIVE_SUCCESS = 'TOGGLE_MEDIA_ACTIVE_SUCCESS';
export const TOGGLE_MEDIA_ACTIVE_FAILURE = 'TOGGLE_MEDIA_ACTIVE_FAILURE';

export const GET_PRIMARY_MEDIA = 'GET_PRIMARY_MEDIA';
export const GET_PRIMARY_MEDIA_SUCCESS = 'GET_PRIMARY_MEDIA_SUCCESS';
export const GET_PRIMARY_MEDIA_FAILURE = 'GET_PRIMARY_MEDIA_FAILURE';

export const UPLOAD_EXPERIENCE_MEDIA = 'UPLOAD_EXPERIENCE_MEDIA';
export const UPLOAD_EXPERIENCE_MEDIA_SUCCESS = 'UPLOAD_EXPERIENCE_MEDIA_SUCCESS';
export const UPLOAD_EXPERIENCE_MEDIA_FAILURE = 'UPLOAD_EXPERIENCE_MEDIA_FAILURE';

export const SET_PRIMARY_MEDIA = 'SET_PRIMARY_MEDIA';
export const SET_PRIMARY_MEDIA_SUCCESS = 'SET_PRIMARY_MEDIA_SUCCESS';
export const SET_PRIMARY_MEDIA_FAILURE = 'SET_PRIMARY_MEDIA_FAILURE';

export const ASSOCIATE_LOCATION_TIMESLOT = 'ASSOCIATE_LOCATION_TIMESLOT';
export const ASSOCIATE_LOCATION_TIMESLOT_SUCCESS = 'ASSOCIATE_LOCATION_TIMESLOT_SUCCESS';
export const ASSOCIATE_LOCATION_TIMESLOT_FAILURE = 'ASSOCIATE_LOCATION_TIMESLOT_FAILURE';

export const UPDATE_LOCATION_TIMESLOT = 'UPDATE_LOCATION_TIMESLOT';
export const UPDATE_LOCATION_TIMESLOT_SUCCESS = 'UPDATE_LOCATION_TIMESLOT_SUCCESS';
export const UPDATE_LOCATION_TIMESLOT_FAILURE = 'UPDATE_LOCATION_TIMESLOT_FAILURE';

export const BULK_ATTACH_LOCATION_TIMESLOTS = 'BULK_ATTACH_LOCATION_TIMESLOTS';
export const BULK_ATTACH_LOCATION_TIMESLOTS_SUCCESS = 'BULK_ATTACH_LOCATION_TIMESLOTS_SUCCESS';
export const BULK_ATTACH_LOCATION_TIMESLOTS_FAILURE = 'BULK_ATTACH_LOCATION_TIMESLOTS_FAILURE';

export const TOGGLE_LOCATION_TIMESLOT = 'TOGGLE_LOCATION_TIMESLOT';
export const TOGGLE_LOCATION_TIMESLOT_SUCCESS = 'TOGGLE_LOCATION_TIMESLOT_SUCCESS';
export const TOGGLE_LOCATION_TIMESLOT_FAILURE = 'TOGGLE_LOCATION_TIMESLOT_FAILURE';
export const TOGGLE_EXPERIENCE_LOCATION = 'TOGGLE_EXPERIENCE_LOCATION';
export const TOGGLE_EXPERIENCE_LOCATION_SUCCESS = 'TOGGLE_EXPERIENCE_LOCATION_SUCCESS';
export const TOGGLE_EXPERIENCE_LOCATION_FAILURE = 'TOGGLE_EXPERIENCE_LOCATION_FAILURE';

export const DISASSOCIATE_LOCATION_TIMESLOT = 'DISASSOCIATE_LOCATION_TIMESLOT';
export const DISASSOCIATE_LOCATION_TIMESLOT_SUCCESS = 'DISASSOCIATE_LOCATION_TIMESLOT_SUCCESS';
export const DISASSOCIATE_LOCATION_TIMESLOT_FAILURE = 'DISASSOCIATE_LOCATION_TIMESLOT_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
