export const GET_REPORTS_DATA = 'GET_REPORTS_DATA';
export const GET_REPORTS_DATA_SUCCESS = 'GET_REPORTS_DATA_SUCCESS';
export const GET_REPORTS_DATA_FAILURE = 'GET_REPORTS_DATA_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
