export const GET_SUPPORT_QUERIES = 'helpdesk/GET_SUPPORT_QUERIES';
export const GET_SUPPORT_QUERIES_SUCCESS = 'helpdesk/GET_SUPPORT_QUERIES_SUCCESS';
export const GET_SUPPORT_QUERIES_FAILURE = 'helpdesk/GET_SUPPORT_QUERIES_FAILURE';

export const RESOLVE_SUPPORT_QUERY = 'helpdesk/RESOLVE_SUPPORT_QUERY';
export const RESOLVE_SUPPORT_QUERY_SUCCESS = 'helpdesk/RESOLVE_SUPPORT_QUERY_SUCCESS';
export const RESOLVE_SUPPORT_QUERY_FAILURE = 'helpdesk/RESOLVE_SUPPORT_QUERY_FAILURE';

export const RESET_STATUS = 'helpdesk/RESET_STATUS';
