export const GET_BOOKINGS_DATA = 'GET_BOOKINGS_DATA';
export const GET_BOOKINGS_DATA_SUCCESS = 'GET_BOOKINGS_DATA_SUCCESS';
export const GET_BOOKINGS_DATA_FAILURE = 'GET_BOOKINGS_DATA_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
