export const GET_PROMOTIONS_DATA = 'GET_PROMOTIONS_DATA';
export const GET_PROMOTIONS_DATA_SUCCESS = 'GET_PROMOTIONS_DATA_SUCCESS';
export const GET_PROMOTIONS_DATA_FAILURE = 'GET_PROMOTIONS_DATA_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
