export const GET_PROMOTIONS_DATA = 'GET_PROMOTIONS_DATA';
export const GET_PROMOTIONS_DATA_SUCCESS = 'GET_PROMOTIONS_DATA_SUCCESS';
export const GET_PROMOTIONS_DATA_FAILURE = 'GET_PROMOTIONS_DATA_FAILURE';

export const CREATE_PROMOTION = 'CREATE_PROMOTION';
export const CREATE_PROMOTION_SUCCESS = 'CREATE_PROMOTION_SUCCESS';
export const CREATE_PROMOTION_FAILURE = 'CREATE_PROMOTION_FAILURE';

export const UPDATE_PROMOTION = 'UPDATE_PROMOTION';
export const UPDATE_PROMOTION_SUCCESS = 'UPDATE_PROMOTION_SUCCESS';
export const UPDATE_PROMOTION_FAILURE = 'UPDATE_PROMOTION_FAILURE';

export const DELETE_PROMOTION = 'DELETE_PROMOTION';
export const DELETE_PROMOTION_SUCCESS = 'DELETE_PROMOTION_SUCCESS';
export const DELETE_PROMOTION_FAILURE = 'DELETE_PROMOTION_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
