export const GET_PAYMENTS_DATA = 'GET_PAYMENTS_DATA';
export const GET_PAYMENTS_DATA_SUCCESS = 'GET_PAYMENTS_DATA_SUCCESS';
export const GET_PAYMENTS_DATA_FAILURE = 'GET_PAYMENTS_DATA_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
