export const GET_REVIEWS_DATA = 'GET_REVIEWS_DATA';
export const GET_REVIEWS_DATA_SUCCESS = 'GET_REVIEWS_DATA_SUCCESS';
export const GET_REVIEWS_DATA_FAILURE = 'GET_REVIEWS_DATA_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
