export const GET_CATEGORY_DATA = 'GET_CATEGORY_DATA';
export const GET_CATEGORY_DATA_SUCCESS = 'GET_CATEGORY_DATA_SUCCESS';
export const GET_CATEGORY_DATA_FAILURE = 'GET_CATEGORY_DATA_FAILURE';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE';

export const REORDER_CATEGORY = 'REORDER_CATEGORY';
export const REORDER_CATEGORY_SUCCESS = 'REORDER_CATEGORY_SUCCESS';
export const REORDER_CATEGORY_FAILURE = 'REORDER_CATEGORY_FAILURE';

export const ASSOCIATE_LOCATION = 'ASSOCIATE_LOCATION';
export const ASSOCIATE_LOCATION_SUCCESS = 'ASSOCIATE_LOCATION_SUCCESS';
export const ASSOCIATE_LOCATION_FAILURE = 'ASSOCIATE_LOCATION_FAILURE';

export const DISASSOCIATE_LOCATION = 'DISASSOCIATE_LOCATION';
export const DISASSOCIATE_LOCATION_SUCCESS = 'DISASSOCIATE_LOCATION_SUCCESS';
export const DISASSOCIATE_LOCATION_FAILURE = 'DISASSOCIATE_LOCATION_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';

// ── Category media ───────────────────────────────────────────────────────────
export const GET_CATEGORY_MEDIA = 'GET_CATEGORY_MEDIA';
export const GET_CATEGORY_MEDIA_SUCCESS = 'GET_CATEGORY_MEDIA_SUCCESS';
export const GET_CATEGORY_MEDIA_FAILURE = 'GET_CATEGORY_MEDIA_FAILURE';

export const ATTACH_CATEGORY_MEDIA = 'ATTACH_CATEGORY_MEDIA';
export const ATTACH_CATEGORY_MEDIA_SUCCESS = 'ATTACH_CATEGORY_MEDIA_SUCCESS';
export const ATTACH_CATEGORY_MEDIA_FAILURE = 'ATTACH_CATEGORY_MEDIA_FAILURE';

export const DETACH_CATEGORY_MEDIA = 'DETACH_CATEGORY_MEDIA';
export const DETACH_CATEGORY_MEDIA_SUCCESS = 'DETACH_CATEGORY_MEDIA_SUCCESS';
export const DETACH_CATEGORY_MEDIA_FAILURE = 'DETACH_CATEGORY_MEDIA_FAILURE';

export const UPDATE_CATEGORY_MEDIA = 'UPDATE_CATEGORY_MEDIA';
export const UPDATE_CATEGORY_MEDIA_SUCCESS = 'UPDATE_CATEGORY_MEDIA_SUCCESS';
export const UPDATE_CATEGORY_MEDIA_FAILURE = 'UPDATE_CATEGORY_MEDIA_FAILURE';

export const TOGGLE_CATEGORY_MEDIA_ACTIVE = 'TOGGLE_CATEGORY_MEDIA_ACTIVE';
export const TOGGLE_CATEGORY_MEDIA_ACTIVE_SUCCESS = 'TOGGLE_CATEGORY_MEDIA_ACTIVE_SUCCESS';
export const TOGGLE_CATEGORY_MEDIA_ACTIVE_FAILURE = 'TOGGLE_CATEGORY_MEDIA_ACTIVE_FAILURE';

export const SET_PRIMARY_CATEGORY_MEDIA = 'SET_PRIMARY_CATEGORY_MEDIA';
export const SET_PRIMARY_CATEGORY_MEDIA_SUCCESS = 'SET_PRIMARY_CATEGORY_MEDIA_SUCCESS';
export const SET_PRIMARY_CATEGORY_MEDIA_FAILURE = 'SET_PRIMARY_CATEGORY_MEDIA_FAILURE';

export const UPLOAD_CATEGORY_MEDIA = 'UPLOAD_CATEGORY_MEDIA';
export const UPLOAD_CATEGORY_MEDIA_SUCCESS = 'UPLOAD_CATEGORY_MEDIA_SUCCESS';
export const UPLOAD_CATEGORY_MEDIA_FAILURE = 'UPLOAD_CATEGORY_MEDIA_FAILURE';
