export const GET_CUSTOMERS_DATA = 'GET_CUSTOMERS_DATA';
export const GET_CUSTOMERS_DATA_SUCCESS = 'GET_CUSTOMERS_DATA_SUCCESS';
export const GET_CUSTOMERS_DATA_FAILURE = 'GET_CUSTOMERS_DATA_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
