export const GET_SUB_CATEGORY_DATA = 'GET_SUB_CATEGORY_DATA';
export const GET_SUB_CATEGORY_DATA_SUCCESS = 'GET_SUB_CATEGORY_DATA_SUCCESS';
export const GET_SUB_CATEGORY_DATA_FAILURE = 'GET_SUB_CATEGORY_DATA_FAILURE';

export const CREATE_SUB_CATEGORY = 'CREATE_SUB_CATEGORY';
export const CREATE_SUB_CATEGORY_SUCCESS = 'CREATE_SUB_CATEGORY_SUCCESS';
export const CREATE_SUB_CATEGORY_FAILURE = 'CREATE_SUB_CATEGORY_FAILURE';

export const UPDATE_SUB_CATEGORY = 'UPDATE_SUB_CATEGORY';
export const UPDATE_SUB_CATEGORY_SUCCESS = 'UPDATE_SUB_CATEGORY_SUCCESS';
export const UPDATE_SUB_CATEGORY_FAILURE = 'UPDATE_SUB_CATEGORY_FAILURE';

export const DELETE_SUB_CATEGORY = 'DELETE_SUB_CATEGORY';
export const DELETE_SUB_CATEGORY_SUCCESS = 'DELETE_SUB_CATEGORY_SUCCESS';
export const DELETE_SUB_CATEGORY_FAILURE = 'DELETE_SUB_CATEGORY_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';

export const ASSOCIATE_LOCATION = 'ASSOCIATE_LOCATION';
export const ASSOCIATE_LOCATION_SUCCESS = 'ASSOCIATE_LOCATION_SUCCESS';
export const ASSOCIATE_LOCATION_FAILURE = 'ASSOCIATE_LOCATION_FAILURE';

export const DISASSOCIATE_LOCATION = 'DISASSOCIATE_LOCATION';
export const DISASSOCIATE_LOCATION_SUCCESS = 'DISASSOCIATE_LOCATION_SUCCESS';
export const DISASSOCIATE_LOCATION_FAILURE = 'DISASSOCIATE_LOCATION_FAILURE';


// ── Sub-category media ───────────────────────────────────────────────────────
export const GET_SUB_CATEGORY_MEDIA = 'GET_SUB_CATEGORY_MEDIA';
export const GET_SUB_CATEGORY_MEDIA_SUCCESS = 'GET_SUB_CATEGORY_MEDIA_SUCCESS';
export const GET_SUB_CATEGORY_MEDIA_FAILURE = 'GET_SUB_CATEGORY_MEDIA_FAILURE';

export const ATTACH_SUB_CATEGORY_MEDIA = 'ATTACH_SUB_CATEGORY_MEDIA';
export const ATTACH_SUB_CATEGORY_MEDIA_SUCCESS = 'ATTACH_SUB_CATEGORY_MEDIA_SUCCESS';
export const ATTACH_SUB_CATEGORY_MEDIA_FAILURE = 'ATTACH_SUB_CATEGORY_MEDIA_FAILURE';

export const DETACH_SUB_CATEGORY_MEDIA = 'DETACH_SUB_CATEGORY_MEDIA';
export const DETACH_SUB_CATEGORY_MEDIA_SUCCESS = 'DETACH_SUB_CATEGORY_MEDIA_SUCCESS';
export const DETACH_SUB_CATEGORY_MEDIA_FAILURE = 'DETACH_SUB_CATEGORY_MEDIA_FAILURE';

export const UPDATE_SUB_CATEGORY_MEDIA = 'UPDATE_SUB_CATEGORY_MEDIA';
export const UPDATE_SUB_CATEGORY_MEDIA_SUCCESS = 'UPDATE_SUB_CATEGORY_MEDIA_SUCCESS';
export const UPDATE_SUB_CATEGORY_MEDIA_FAILURE = 'UPDATE_SUB_CATEGORY_MEDIA_FAILURE';

export const TOGGLE_SUB_CATEGORY_MEDIA_ACTIVE = 'TOGGLE_SUB_CATEGORY_MEDIA_ACTIVE';
export const TOGGLE_SUB_CATEGORY_MEDIA_ACTIVE_SUCCESS = 'TOGGLE_SUB_CATEGORY_MEDIA_ACTIVE_SUCCESS';
export const TOGGLE_SUB_CATEGORY_MEDIA_ACTIVE_FAILURE = 'TOGGLE_SUB_CATEGORY_MEDIA_ACTIVE_FAILURE';

export const SET_PRIMARY_SUB_CATEGORY_MEDIA = 'SET_PRIMARY_SUB_CATEGORY_MEDIA';
export const SET_PRIMARY_SUB_CATEGORY_MEDIA_SUCCESS = 'SET_PRIMARY_SUB_CATEGORY_MEDIA_SUCCESS';
export const SET_PRIMARY_SUB_CATEGORY_MEDIA_FAILURE = 'SET_PRIMARY_SUB_CATEGORY_MEDIA_FAILURE';

export const UPLOAD_SUB_CATEGORY_MEDIA = 'UPLOAD_SUB_CATEGORY_MEDIA';
export const UPLOAD_SUB_CATEGORY_MEDIA_SUCCESS = 'UPLOAD_SUB_CATEGORY_MEDIA_SUCCESS';
export const UPLOAD_SUB_CATEGORY_MEDIA_FAILURE = 'UPLOAD_SUB_CATEGORY_MEDIA_FAILURE';
