export const GET_FAQ_DATA = 'GET_FAQ_DATA';
export const GET_FAQ_DATA_SUCCESS = 'GET_FAQ_DATA_SUCCESS';
export const GET_FAQ_DATA_FAILURE = 'GET_FAQ_DATA_FAILURE';

export const CREATE_FAQ = 'CREATE_FAQ';
export const CREATE_FAQ_SUCCESS = 'CREATE_FAQ_SUCCESS';
export const CREATE_FAQ_FAILURE = 'CREATE_FAQ_FAILURE';

export const UPDATE_FAQ = 'UPDATE_FAQ';
export const UPDATE_FAQ_SUCCESS = 'UPDATE_FAQ_SUCCESS';
export const UPDATE_FAQ_FAILURE = 'UPDATE_FAQ_FAILURE';

export const DELETE_FAQ = 'DELETE_FAQ';
export const DELETE_FAQ_SUCCESS = 'DELETE_FAQ_SUCCESS';
export const DELETE_FAQ_FAILURE = 'DELETE_FAQ_FAILURE';

export const TOGGLE_FAQ = 'TOGGLE_FAQ';
export const TOGGLE_FAQ_SUCCESS = 'TOGGLE_FAQ_SUCCESS';
export const TOGGLE_FAQ_FAILURE = 'TOGGLE_FAQ_FAILURE';

export const REORDER_FAQ = 'REORDER_FAQ';
export const REORDER_FAQ_SUCCESS = 'REORDER_FAQ_SUCCESS';
export const REORDER_FAQ_FAILURE = 'REORDER_FAQ_FAILURE';

export const RESET_FAQ_STATUS = 'RESET_FAQ_STATUS';
