export const GET_NOTIFICATIONS_DATA = 'notifications/GET_NOTIFICATIONS_DATA';
export const GET_NOTIFICATIONS_DATA_SUCCESS = 'notifications/GET_NOTIFICATIONS_DATA_SUCCESS';
export const GET_NOTIFICATIONS_DATA_FAILURE = 'notifications/GET_NOTIFICATIONS_DATA_FAILURE';

export const RESET_STATUS = 'notifications/RESET_STATUS';
